Front End Updates
tyberious-1/codebuddiesMUD pull request #24
Opened 2018-11-23 21:07 UTC by angelocordon

Set up front end architecture with Webpack; Vue can easily be installed in the future by running `docker-compose exec web rails webpack:install:vue`. 

Dockerfile and Docker Compose file is restructured to use a Docker Image that includes Ruby, Rails + NodeJS. This allows us to use Yarn as well against the Docker `web` service. Additionally, this includes a fix for the server.pid issue (#13).

Lastly, minimalistic updates to our welcome screen:

![image](https://user-images.githubusercontent.com/3891869/48960239-b9800680-ef1f-11e8-84af-f48380a4a55f.png)

2018-11-24 14:57 UTC, stain88 requested changes

2018-11-24 14:57 UTC, stain88 commented on README.md
Think we need something else here for `yarn`. I get

```
========================================
  Your Yarn packages are out of date!
  Please run `yarn install` to update.
========================================
```

2018-12-02 20:09 UTC, stain88 approved these changes

2018-12-02 20:10 UTC, stain88 commented
I'm happy with the current situation

2018-12-02 21:01 UTC, jtkaufman737 commented
Looking good to me as well.

2018-12-02 21:01 UTC, jtkaufman737 approved these changes

2018-12-02 21:15 UTC, merged